FROM debian:{tag}

# use mirrors.ocf.berkeley.edu
RUN sed -i 's|httpredir\.debian\.org|mirrors.ocf.berkeley.edu|g; \
        s|security\.debian\.org|mirrors.ocf.berkeley.edu/debian-security|g' \
        /etc/apt/sources.list

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
            ca-certificates \
            curl \
            vim-tiny \
            zsh \
        && rm -rf /var/lib/apt/lists/*

# add ocf apt repo                                                 # if:jessie
RUN curl https://apt.ocf.berkeley.edu/pubkey.gpg | apt-key add - \ # if:jessie
        && echo 'deb http://apt.ocf.berkeley.edu/ {tag} main' \    # if:jessie
              >> /etc/apt/sources.list                             # if:jessie

# add deb-src entries
RUN sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list
