FROM {{base}}

# use mirrors.ocf.berkeley.edu
RUN sed -ri 's!(httpredir|deb)\.debian\.org!mirrors.ocf.berkeley.edu!g; \
        s!security\.debian\.org!mirrors.ocf.berkeley.edu!g' \
        /etc/apt/sources.list

# Install a few packages so that the OCF apt key can be added and so that any
# pre-package installation commands work
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates curl gnupg


{% if ocf_apt_repo_dist %}
# add ocf apt repo
RUN curl https://apt.ocf.berkeley.edu/pubkey.gpg | apt-key add - && \
    echo 'deb http://apt.ocf.berkeley.edu/ {{ocf_apt_repo_dist}} main' \
      >> /etc/apt/sources.list
{% endif %}

{% if backport_dist %}
RUN echo 'Package: *\nPin: release n={{backport_dist}}\nPin-Priority: 200' \
      > /etc/apt/preferences.d/backports.pref
RUN echo 'deb http://mirrors.ocf.berkeley.edu/debian/ {{backport_dist}} main' \
      >> /etc/apt/sources.list
{% if ocf_apt_repo_dist %}
RUN echo 'deb http://apt.ocf.berkeley.edu/ {{backport_dist}} main' \
      >> /etc/apt/sources.list
{% endif %}
{% endif %}

# add deb-src entries
RUN sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list

# Run package installation after all apt repos have been added
{% if packages %}
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        {% for package in packages|sort %} {{package}} {% endfor %} \
    && rm -rf /var/lib/apt/lists/*
{% endif %}

{% if dumb_init_version %}
RUN curl -sLo /tmp/dumb-init.deb \
        https://github.com/Yelp/dumb-init/releases/download/v{{dumb_init_version}}/dumb-init_{{dumb_init_version}}_amd64.deb \
    && dpkg -i /tmp/dumb-init.deb \
    && rm /tmp/dumb-init.deb \
    && apt-get clean
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
{% endif %}

{% if ldap %}
COPY libnss-ldap.conf /etc/
COPY nsswitch.conf /etc/
COPY ldap.conf /etc/
RUN mkdir -p /etc/ldap/ && ln -fs /etc/ldap.conf /etc/ldap/ldap.conf
{% endif %}

{% if kerberos %}
COPY krb5.conf /etc/
{% endif %}

{% if mail %}
COPY ssmtp.conf /etc/ssmtp/
{% endif %}

RUN mkdir /opt/share

{% if utils %}
RUN mkdir /opt/share/utils
RUN curl -sL https://github.com/ocf/utils/archive/master.tar.gz | tar -C /opt/share/utils --strip-components=1 -xzf-
{% endif %}

# Set locale
RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
RUN /usr/sbin/locale-gen
ENV LANG en_US.UTF-8

# Set timezone through a workaround
# https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
RUN ln -fs /usr/share/zoneinfo/US/Pacific /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

COPY incommon-intermediate.crt /etc/ssl/certs/

CMD ["/bin/bash"]

# vim: ft=jinja
