FROM {{base}}

# use mirrors.ocf.berkeley.edu
RUN sed -ri 's!(httpredir|deb)\.debian\.org!mirrors.ocf.berkeley.edu!g; \
        s!security\.debian\.org!mirrors.ocf.berkeley.edu/debian-security!g' \
        /etc/apt/sources.list

{% if packages %}
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        {% for package in packages|sort %} {{package}} {% endfor %} \
    && rm -rf /var/lib/apt/lists/*
{% endif %}

{% if dumb_init_version %}
RUN curl -sLo /tmp/dumb-init.deb \
        https://github.com/Yelp/dumb-init/releases/download/v{{dumb_init_version}}/dumb-init_{{dumb_init_version}}_amd64.deb \
    && dpkg -i /tmp/dumb-init.deb \
    && rm /tmp/dumb-init.deb \
    && apt-get clean
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
{% endif %}

{% if ocf_apt_repo_dist %}
# add ocf apt repo
RUN curl https://apt.ocf.berkeley.edu/pubkey.gpg | apt-key add - && \
    echo 'deb http://apt.ocf.berkeley.edu/ {{ocf_apt_repo_dist}} main' \
      >> /etc/apt/sources.list
{% endif %}

# add deb-src entries
RUN sed 's/^deb /deb-src /' /etc/apt/sources.list >> /etc/apt/sources.list

{% if ldap %}
COPY libnss-ldap.conf /etc/
COPY nsswitch.conf /etc/
{% endif %}

{% if kerberos %}
COPY krb5.conf /etc/
{% endif %}

{% if mail %}
COPY ssmtp.conf /etc/ssmtp/
{% endif %}

# Set locale
RUN echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
RUN /usr/sbin/locale-gen
ENV LANG en_US.UTF-8

# Set timezone through a workaround
# https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
RUN ln -fs /usr/share/zoneinfo/US/Pacific /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

COPY incommon-intermediate.crt /etc/ssl/certs/

CMD ["/bin/bash"]

# vim: ft=jinja
