RELEASES := wheezy jessie stretch sid

.PHONY: Dockerfiles
Dockerfiles: $(RELEASES)

$(RELEASES): Dockerfile.in
	mkdir -p "$@"
	echo "# DO NOT EDIT THIS FILE" > "$@/Dockerfile"
	printf '# IT IS AUTOMATICALLY GENERATED\n\n' >> "$@/Dockerfile"
	sed "/# no:$@/d; s/{tag}/$@/g; s/\\s*# no:[a-z]\\+.*//g" Dockerfile.in \
	  >> "$@/Dockerfile"

clean:
	$(RM) -r $(RELEASES)
