RELEASES := wheezy jessie stretch sid

.PHONY: Dockerfiles
Dockerfiles: $(RELEASES)

$(RELEASES): Dockerfile.in
	mkdir -p "$@"
	cp Dockerfile.in "$@/Dockerfile.out"
	# Substitute {tag} with its actual value
	sed -i "s/{tag}/$@/g" "$@/Dockerfile.out"
	# Delete lines which don't match no: specifiers
	sed -i "/# no:$@/d" "$@/Dockerfile.out"
	# Keep lines which match if: specifiers, by removing those specifiers
	# so the line doesn't get deleted later
	sed -ri "/# if:$@/ {s/\\s*# if:[a-z]+.*//g; }" "$@/Dockerfile.out"
	# Remove remaining no: specifiers, because they must match
	sed -ri 's/\s*# no:[a-z]+.*//g' "$@/Dockerfile.out"
	# Delete lines with if: specifiers, they must not have matched
	sed -ri '/\s*# if:[a-z]+.*/d' "$@/Dockerfile.out"

	echo "# DO NOT EDIT THIS FILE" > "$@/Dockerfile"
	printf '# IT IS AUTOMATICALLY GENERATED\n\n' >> "$@/Dockerfile"
	cat "$@/Dockerfile.out" >> "$@/Dockerfile"
	$(RM) "$@/Dockerfile.out"

clean:
	$(RM) -r $(RELEASES)
